name: simple_blog_flutter
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  google_fonts: ^8.0.0
  image_picker: ^1.2.1
  image_picker_for_web: ^3.1.1
  intl: ^0.20.2
  provider: ^6.1.5+1
  smooth_page_indicator: ^2.0.1
  supabase_flutter: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
